import streamlit as st
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd

# Autenticação com Google Sheets
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
credentials = ServiceAccountCredentials.from_json_keyfile_dict(st.secrets["gcp_service_account"], scope)
client = gspread.authorize(credentials)

# Acesse a planilha
spreadsheet = client.open_by_url(st.secrets["spreadsheet_url"])
worksheet = spreadsheet.sheet1

# Carrega os dados
data = worksheet.get_all_records()
df = pd.DataFrame(data)

# Interface Streamlit
st.title("📊 Monitoramento da Linha de Cuidado")
st.dataframe(df)
